version = 0.1
[default]
[default.global.parameters]
parameter_overrides = "ALLOWORIGIN=http://localhost:3000 MYSQLHOSTNAME=lambda-study-db MYSQLPASSWORD=rootpass MYSQLPORTNO=3307 MYSQLUSER=root"

[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o0tl51qoyv0e"
s3_prefix = "sam-app"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"

parameter_overrides = "ALLOWORIGIN=http://s3.maruuuui.tk MYSQLHOSTNAME=todo-database.c6zossjgd3tu.ap-northeast-1.rds.amazonaws.com MYSQLPASSWORD=todopass MYSQLPORTNO=3306 MYSQLUSER=admin"
image_repositories = ["HelloWorldFunction=674302997061.dkr.ecr.ap-northeast-1.amazonaws.com/samapp7427b055/helloworldfunction19d43fc4repo"]
